import React from 'react';
import { View, Text, StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';
import ScreenHeader from '../../components/ScreenHeader';
import { useNavigation } from '@react-navigation/native';

export default function MyPayrollScreen() {
  const navigation = useNavigation<any>();
  return (
    <View style={{ flex: 1, backgroundColor: colors.bg }}>
      <ScreenHeader title="Payroll" currentRoute="Payroll" onNavigate={(route) => navigation.navigate(route)} />
      <View style={s.container}>
        <Text style={s.title}>My Payroll</Text>
      <View style={s.card}>
        <Text style={s.icon}>₹</Text>
        <Text style={s.heading}>Coming Soon</Text>
        <Text style={s.sub}>Your payslips will appear here once generated by admin.</Text>
      </View>
      </View>
    </View>
  );
}

const s = StyleSheet.create({
  container: { padding: 16 },
  title: { fontSize: 22, fontWeight: '800', color: colors.navy950, marginBottom: 20 },
  card: { backgroundColor: '#fff', borderRadius: 16, padding: 40, alignItems: 'center', borderWidth: 1, borderColor: colors.slate[200] },
  icon: { fontSize: 48, fontWeight: '800', color: colors.brand600 },
  heading: { fontSize: 20, fontWeight: '700', color: colors.slate[800], marginTop: 12 },
  sub: { fontSize: 14, color: colors.slate[500], marginTop: 6, textAlign: 'center' },
});
